### ISSUE TITLE
Connected components identifying table header color in pdf

### ISSUE THREAD

**Issue by Sunitha2610** [ahmetozlu/signature_extractor#7]
Code identify table header and other shaped components. how to avoid those components?
![Connected component image](https://user-images.githubusercontent.com/52991576/106425840-8552e980-648a-11eb-8311-6afd97506f5f.PNG)

**Comment by ahmetozlu** [comment]
The connected pixels, have the size bigger than a threshold value, should be removed (skip to detect) so you can get rid of these outliars [in other words, **_remove the connected pixels are bigger than threshold_**]. This feature have been just developed. Please check these lines and try again:

- [signature_extractor.py line66-77](https://github.com/ahmetozlu/signature_extractor/blob/master/signature_extractor.py#L66-L70) 
- [sample_project/signature_extractor.py line79-83](https://github.com/ahmetozlu/signature_extractor/blob/master/sample_project/signature_extractor.py#L79-L83)
